version: "3.8"

services:
  api-gateway:
    build: ./api_gateway
    environment:
      API_GATEWAY_PORT: 8000
      SERVICE_A_URL: http://service-a:4001
      SERVICE_B_URL: http://service-b:4002
      SERVICE_C_URL: http://service-c:4003
      SERVICE_D_URL: http://service-d:4004
    depends_on:
      - service-a
      - service-b
      - service-c
      - service-d
    networks:
      - app-network

  service-a:
    build: ./service_a
    environment:
      PORT: 4001
    networks:
      - app-network

  service-b:
    build: ./service_b
    environment:
      PORT: 4002
    networks:
      - app-network

  service-c:
    build: ./service_c
    environment:
      PORT: 4003
    networks:
      - app-network

  service-d:
    build: ./service_d
    environment:
      PORT: 4004
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
