name: Deploy Microservices to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS and deploy Docker containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /home/ubuntu/test_docker_ms_cicd_deployment_v1
            git pull origin main
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up --build -d
